server:
  shutdown: graceful

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  lifecycle:
    timeout-per-shutdown-phase: 20s

logging:
  level:
    root: INFO
    com.necoocean.tools: INFO

tools:
  security:
    ip-hash-salt: ${IP_HASH_SALT}
